//----------------------------------------------------------------------------------------------------------------------------------

#include "tilegrid.h"

#include "clkdiv_bk1.h"
#include "clkdiv_bk2.h"
#include "clkdiv_bk3.h"
#include "clkdiv_bk4.h"
#include "clkdiv_bk5.h"
#include "clkdiv_bk6.h"
#include "clkdiv_bk7.h"
#include "clkdiv_bk8.h"
#include "emb32k_b0.h"
#include "emb32k_b1.h"
#include "emb_slice.h"
#include "gclk_csb.h"
#include "gclk_ctmux_l.h"
#include "gclk_ctmux_u.h"
#include "gclk_premux_b.h"
#include "gclk_premux_l.h"
#include "gclk_premux_r.h"
#include "gclk_premux_t.h"
#include "gclk_spine.h"
#include "ioclk_bk1.h"
#include "ioclk_bk2.h"
#include "ioclk_bk3.h"
#include "ioclk_bk4.h"
#include "ioclk_bk5.h"
#include "ioclk_bk6.h"
#include "ioclk_bk7.h"
#include "ioclk_bk8.h"
#include "iol_pair_l.h"
#include "iol_pair_r.h"
#include "iol_quad_b.h"
#include "iol_quad_l.h"
#include "iol_quad_r.h"
#include "iol_quad_t.h"
#include "ios_bankref_bl.h"
#include "ios_bankref_br.h"
#include "ios_bankref_l.h"
#include "ios_bankref_r.h"
#include "ios_bankref_tl.h"
#include "ios_bankref_tr.h"
#include "mult.h"
#include "osc.h"
#include "pib.h"
#include "plb.h"
#include "pll0.h"
#include "pll2.h"

//----------------------------------------------------------------------------------------------------------------------------------

