/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	/home/peter/Data/Anlogic_projects/FNIRSI_1013D/al_ip/pll.v
 ** Date	:	2022 09 10
 ** TD version	:	5.0.28716
\************************************************************/

///////////////////////////////////////////////////////////////////////////////
//	Input frequency:             50.000Mhz
//	Clock multiplication factor: 20
//	Clock division factor:       1
//	Clock information:
//		Clock name	| Frequency 	| Phase shift
//		C0        	| 200.000000MHZ	| 0  DEG     
///////////////////////////////////////////////////////////////////////////////
`timescale 1 ns / 100 fs

module pll(refclk,
		reset,
		clk0_out);

	input refclk;
	input reset;
	output clk0_out;


	AL_PHY_PLL #(.DPHASE_SOURCE("DISABLE"),
		.FIN("50.000"),
		.FEEDBK_MODE("NOCOMP"),
		.FEEDBK_PATH("VCO_PHASE_0"),
		.STDBY_ENABLE("DISABLE"),
		.PLLRST_ENA("ENABLE"),
		.SYNC_ENABLE("DISABLE"),
		.DERIVE_PLL_CLOCKS("DISABLE"),
		.GEN_BASIC_CLOCK("DISABLE"),
		.GMC_GAIN("4"),
		.ICP_CURRENT(11),
		.KVCO("4"),
		.LPF_CAPACITOR("1"),
		.LPF_RESISTOR(4),
		.REFCLK_DIV(1),
		.FBCLK_DIV(20),
		.CLKC0_ENABLE("ENABLE"),
		.CLKC0_DIV(5),
		.CLKC0_CPHASE(4),
		.CLKC0_FPHASE("0")	)
	pll_inst (.refclk(refclk),
		.pllreset(reset),
		.stdby(1'b0),
		.ext_lock(open),
		.load_reg(1'b0),
		.scanclk(1'b0),
		.phaseupdown(1'b0),
		.phasestep(1'b0),
		.phcntsel(3'b000),
		.phasedone(open),
		.fbclk(1'b0),
		.clkc({open, open, open, open, clk0_out}));

endmodule
