//----------------------------------------------------------------------------------------------------------------------------------

typedef struct tagNETRENAME    NETRENAME,   *pNETRENAME;

//----------------------------------------------------------------------------------------------------------------------------------

struct tagNETRENAME
{
  char *net_name;
  char *new_name;
};

//----------------------------------------------------------------------------------------------------------------------------------

#define NET_RENAMING

//----------------------------------------------------------------------------------------------------------------------------------

NETRENAME net_renaming_table[] =
{
  { "net_46",          "sample_addr_11"       },
  { "net_42",          "sample_addr_10"       },
  { "net_44",          "sample_addr_9"        },
  { "net_43",          "sample_addr_8"        },
  { "net_45",          "sample_addr_7"        },
  { "net_36",          "sample_addr_6"        },
  { "net_38",          "sample_addr_5"        },
  { "net_37",          "sample_addr_4"        },
  { "net_39",          "sample_addr_3"        },
  { "net_33",          "sample_addr_2"        },
  { "net_35",          "sample_addr_1"        },
  { "net_34",          "sample_addr_0"        },
  { "net_529",         "read_addr_11"         },
  { "net_17",          "read_addr_10"         },
  { "net_53",          "read_addr_9"          },
  { "net_290",         "read_addr_8"          },
  { "net_301",         "read_addr_7"          },
  { "net_373",         "read_addr_6"          },
  { "net_371",         "read_addr_5"          },
  { "net_377",         "read_addr_4"          },
  { "net_48",          "read_addr_3"          },
  { "net_300",         "read_addr_2"          },
  { "net_289",         "read_addr_1"          },
  { "net_51",          "read_addr_0"          },

  { "net_16",          "read_addr_l10"        },
  { "net_527",         "read_addr_l11"        },

  { "net_168",         "sample_write_enable"  },
  { "net_730",         "sample_write_clock"   },
  { "net_18",          "sample_read_clock"    },
  { "net_181",         "sample_read_enable"   },
  { "net_886",         "o_adc2B_d_7"          },
  { "net_885",         "o_adc2B_d_6"          },
  { "net_884",         "o_adc2B_d_5"          },
  { "net_882",         "o_adc2B_d_4"          },
  { "net_883",         "o_adc2B_d_3"          },
  { "net_140",         "o_adc2B_d0_2"         },
  { "net_147",         "o_adc2B_d0_1"         },
  { "net_146",         "o_adc2B_d0_0"         },
  { "net_144",         "o_adc2A_d0_7"         },
  { "net_145",         "o_adc2A_d0_6"         },
  { "net_143",         "o_adc2A_d0_5"         },
  { "net_142",         "o_adc2A_d0_4"         },
  { "net_139",         "o_adc2A_d0_3"         },
  { "net_141",         "o_adc2A_d0_2"         },
  { "net_80",          "o_adc2A_d0_1"         },
  { "net_84",          "o_adc2A_d0_0"         },
  { "net_83",          "o_adc1B_d0_7"         },
  { "net_81",          "o_adc1B_d0_6"         },
  { "net_82",          "o_adc1B_d0_5"         },
  { "net_79",          "o_adc1B_d0_4"         },
  { "net_77",          "o_adc1B_d0_3"         },
  { "net_76",          "o_adc1B_d0_2"         },
  { "net_78",          "o_adc1B_d0_1"         },
  { "net_850",         "o_adc1B_d0_0"         },
  { "net_853",         "o_adc1A_d0_7"         },
  { "net_854",         "o_adc1A_d0_6"         },
  { "net_852",         "o_adc1A_d0_5"         },
  { "net_851",         "o_adc1A_d0_4"         },
  { "net_847",         "o_adc1A_d0_3"         },
  { "net_848",         "o_adc1A_d0_2"         },
  { "net_846",         "o_adc1A_d0_1"         },
  { "net_849",         "o_adc1A_d0_0"         },
  { "net_134",         "o_adc2B_d1_2"         },
  { "net_135",         "o_adc2B_d1_1"         },
  { "net_138",         "o_adc2B_d1_0"         },
  { "net_137",         "o_adc2A_d1_7"         },
  { "net_136",         "o_adc2A_d1_6"         },
  { "net_132",         "o_adc2A_d1_5"         },
  { "net_133",         "o_adc2A_d1_4"         },
  { "net_130",         "o_adc2A_d1_3"         },
  { "net_131",         "o_adc2A_d1_2"         },
  { "net_91",          "o_adc2A_d1_1"         },
  { "net_90",          "o_adc2A_d1_0"         },
  { "net_89",          "o_adc1B_d1_7"         },
  { "net_93",          "o_adc1B_d1_6"         },
  { "net_92",          "o_adc1B_d1_5"         },
  { "net_85",          "o_adc1B_d1_4"         },
  { "net_87",          "o_adc1B_d1_3"         },
  { "net_88",          "o_adc1B_d1_2"         },
  { "net_86",          "o_adc1B_d1_1"         },
  { "net_857",         "o_adc1B_d1_0"         },
  { "net_863",         "o_adc1A_d1_7"         },
  { "net_862",         "o_adc1A_d1_6"         },
  { "net_860",         "o_adc1A_d1_5"         },
  { "net_861",         "o_adc1A_d1_4"         },
  { "net_858",         "o_adc1A_d1_3"         },
  { "net_859",         "o_adc1A_d1_2"         },
  { "net_856",         "o_adc1A_d1_1"         },
  { "net_855",         "o_adc1A_d1_0"         },
  { "net_116",         "o_adc2B_d2_2"         },
  { "net_119",         "o_adc2B_d2_1"         },
  { "net_120",         "o_adc2B_d2_0"         },
  { "net_118",         "o_adc2A_d2_7"         },
  { "net_117",         "o_adc2A_d2_6"         },
  { "net_114",         "o_adc2A_d2_5"         },
  { "net_115",         "o_adc2A_d2_4"         },
  { "net_113",         "o_adc2A_d2_3"         },
  { "net_112",         "o_adc2A_d2_2"         },
  { "net_106",         "o_adc2A_d2_1"         },
  { "net_111",         "o_adc2A_d2_0"         },
  { "net_108",         "o_adc1B_d2_7"         },
  { "net_109",         "o_adc1B_d2_6"         },
  { "net_110",         "o_adc1B_d2_5"         },
  { "net_107",         "o_adc1B_d2_4"         },
  { "net_103",         "o_adc1B_d2_3"         },
  { "net_104",         "o_adc1B_d2_2"         },
  { "net_105",         "o_adc1B_d2_1"         },
  { "net_877",         "o_adc1B_d2_0"         },
  { "net_881",         "o_adc1A_d2_7"         },
  { "net_878",         "o_adc1A_d2_6"         },
  { "net_879",         "o_adc1A_d2_5"         },
  { "net_880",         "o_adc1A_d2_4"         },
  { "net_876",         "o_adc1A_d2_3"         },
  { "net_875",         "o_adc1A_d2_2"         },
  { "net_873",         "o_adc1A_d2_1"         },
  { "net_874",         "o_adc1A_d2_0"         },
  { "net_126",         "o_adc2B_d3_2"         },
  { "net_125",         "o_adc2B_d3_1"         },
  { "net_127",         "o_adc2B_d3_0"         },
  { "net_128",         "o_adc2A_d3_7"         },
  { "net_129",         "o_adc2A_d3_6"         },
  { "net_121",         "o_adc2A_d3_5"         },
  { "net_123",         "o_adc2A_d3_4"         },
  { "net_124",         "o_adc2A_d3_3"         },
  { "net_122",         "o_adc2A_d3_2"         },
  { "net_95",          "o_adc2A_d3_1"         },
  { "net_102",         "o_adc2A_d3_0"         },
  { "net_99",          "o_adc1B_d3_7"         },
  { "net_100",         "o_adc1B_d3_6"         },
  { "net_101",         "o_adc1B_d3_5"         },
  { "net_98",          "o_adc1B_d3_4"         },
  { "net_94",          "o_adc1B_d3_3"         },
  { "net_96",          "o_adc1B_d3_2"         },
  { "net_97",          "o_adc1B_d3_1"         },
  { "net_871",         "o_adc1B_d3_0"         },
  { "net_872",         "o_adc1A_d3_7"         },
  { "net_868",         "o_adc1A_d3_6"         },
  { "net_869",         "o_adc1A_d3_5"         },
  { "net_870",         "o_adc1A_d3_4"         },
  { "net_867",         "o_adc1A_d3_3"         },
  { "net_866",         "o_adc1A_d3_2"         },
  { "net_865",         "o_adc1A_d3_1"         },
  { "net_864",         "o_adc1A_d3_0"         },
  { "net_481",         "mcu_data_dir"         },
  { "net_365",         "o_mcu_d_0"            },
  { "net_357",         "o_mcu_d_1"            },
  { "net_551",         "o_mcu_d_2"            },
  { "net_344",         "o_mcu_d_3"            },
  { "net_557",         "o_mcu_d_4"            },
  { "net_358",         "o_mcu_d_5"            },
  { "net_362",         "o_mcu_d_6"            },
  { "net_438",         "o_mcu_d_7"            },
  { "net_458",         "calib_1khz"           },
  { "net_436",         "pwm_display"          },
  { "net_571",         "ac_dc_1"              },
  { "net_471",         "ac_dc_2"              },
  { "net_713",         "offset_1"             },
  { "net_474",         "offset_2"             },
  { "net_844",         "relay1_1"             },
  { "net_845",         "relay1_2"             },
  { "net_843",         "relay1_3"             },
  { "net_563",         "relay2_1"             },
  { "net_842",         "relay2_2"             },
  { "net_841",         "relay2_3"             },
  { "net_840",         "adc1_encA"            },
  { "net_729",         "adc1_encB"            },
  { "net_839",         "adc2_encA"            },
  { "net_1219",        "adc2_encB"            },

  { "net_991",         "o_i2c_sda"            },
  { "net_972",         "i2c_sda_dir"          },
  { "net_1418",        "i_i2c_cmd68_b0"       },
  { "net_786",         "i_i2c_cmd69_b0"       },
  { "net_1412",        "i_i2c_cmd6A_b0"       },
  { "net_988",         "i_i2c_cmd6B_b0"       },
  { "net_1382",        "i_i2c_cmd6C_b0"       },
  { "net_965",         "i_i2c_cmd6D_b0"       },
  { "net_1295",        "i_i2c_cmd6E_b0"       },

  { "net_182",         "trigger_mode"         },
  { "net_427",         "trigger_channel"      },
  { "net_457",         "trigger_edge"         },
  { "net_167",         "sampling_enable"      },
  { "net_261",         "sampling_reset"       },

  { "net_336",         "trigger_level_b0"     },
  { "net_326",         "trigger_level_b1"     },
  { "net_334",         "trigger_level_b2"     },
  { "net_327",         "trigger_level_b3"     },
  { "net_243",         "trigger_level_b4"     },
  { "net_246",         "trigger_level_b5"     },
  { "net_22",          "trigger_level_b6"     },
  { "net_161",         "trigger_level_b7"     },

  { "net_708",         "cmd_write_enable"     },
  { "net_703",         "cmd_b0"               },
  { "net_701",         "cmd_b1"               },
  { "net_270",         "cmd_b2"               },
  { "net_556",         "cmd_b3"               },
  { "net_444",         "cmd_b4"               },
  { "net_448",         "cmd_b5"               },
  { "net_447",         "cmd_b6"               },
  { "net_449",         "cmd_b7"               },

  { "net_464",         "disp_bright_b0"       },
  { "net_462",         "disp_bright_b1"       },
  { "net_411",         "disp_bright_b2"       },
  { "net_408",         "disp_bright_b3"       },
  { "net_412",         "disp_bright_b4"       },
  { "net_526",         "disp_bright_b5"       },
  { "net_441",         "disp_bright_b6"       },
  { "net_520",         "disp_bright_b7"       },
  { "net_319",         "disp_bright_b8"       },
  { "net_404",         "disp_bright_b9"       },
  { "net_174",         "disp_bright_b10"      },
  { "net_420",         "disp_bright_b11"      },
  { "net_342",         "disp_bright_b12"      },
  { "net_346",         "disp_bright_b13"      },
  { "net_532",         "disp_bright_b14"      },
  { "net_173",         "disp_bright_b15"      },

  { "net_521",         "db_cnt_b15"           },
  { "net_516",         "db_cnt_b14"           },
  { "net_518",         "db_cnt_b13"           },
  { "net_517",         "db_cnt_b12"           },
  { "net_519",         "db_cnt_b11"           },
  { "net_512",         "db_cnt_b10"           },
  { "net_514",         "db_cnt_b9"            },
  { "net_513",         "db_cnt_b8"            },
  { "net_515",         "db_cnt_b7"            },
  { "net_505",         "db_cnt_b6"            },
  { "net_507",         "db_cnt_b5"            },
  { "net_506",         "db_cnt_b4"            },
  { "net_508",         "db_cnt_b3"            },
  { "net_501",         "db_cnt_b2"            },
  { "net_503",         "db_cnt_b1"            },
  { "net_502",         "db_cnt_b0"            },

  { "net_465",         "db_match_a"           },
  { "net_409",         "db_match_b"           },
  { "net_410",         "db_match_c"           },
  { "net_413",         "db_match_d"           },
  { "net_414",         "db_match_e"           },
  { "net_443",         "db_match_f"           },
  { "net_524",         "db_match_g"           },
  { "net_523",         "db_match_h"           },
  { "net_323",         "db_match_i"           },
  { "net_322",         "db_match_j"           },
  { "net_407",         "db_match_k"           },
  { "net_406",         "db_match_l"           },
  { "net_418",         "db_match_m"           },
  { "net_417",         "db_match_n"           },
  { "net_343",         "db_match_o"           },
  { "net_347",         "db_match_p"           },
  { "net_528",         "db_match_q"           },
  { "net_531",         "db_match_r"           },
  { "net_417",         "db_match_s"           },

  { "net_509",         "pwm_enable"           },
  { "net_753",         "pwm_enable_a"         },
  { "net_668",         "pwm_enable_b"         },

  { "net_775",         "ch1_offset_b0"        },
  { "net_1114",        "ch1_offset_b1"        },
  { "net_1113",        "ch1_offset_b2"        },
  { "net_1117",        "ch1_offset_b3"        },
  { "net_1107",        "ch1_offset_b4"        },
  { "net_774",         "ch1_offset_b5"        },
  { "net_768",         "ch1_offset_b6"        },
  { "net_769",         "ch1_offset_b7"        },
  { "net_756",         "ch1_offset_b8"        },
  { "net_758",         "ch1_offset_b9"        },
  { "net_722",         "ch1_offset_b10"       },
  { "net_951",         "ch1_offset_b11"       },
  { "net_941",         "ch1_offset_b12"       },
  { "net_940",         "ch1_offset_b13"       },
  { "net_953",         "ch1_offset_b14"       },
  { "net_717",         "ch1_offset_b15"       },

  { "net_686",         "offset1_pwm_r15"      },   //Registers for the counter and input in to the adder
  { "net_1102",        "offset1_pwm_r14"      },
  { "net_762",         "offset1_pwm_r13"      },
  { "net_673",         "offset1_pwm_r12"      },
  { "net_672",         "offset1_pwm_r11"      },
  { "net_683",         "offset1_pwm_r10"      },
  { "net_541",         "offset1_pwm_r9"       },
  { "net_1099",        "offset1_pwm_r8"       },
  { "net_675",         "offset1_pwm_r7"       },
  { "net_1101",        "offset1_pwm_r6"       },
  { "net_1105",        "offset1_pwm_r5"       },
  { "net_664",         "offset1_pwm_r4"       },
  { "net_660",         "offset1_pwm_r3"       },
  { "net_761",         "offset1_pwm_r2"       },
  { "net_661",         "offset1_pwm_r1"       },
  { "net_662",         "offset1_pwm_r0"       },

  { "net_687",         "offset1_pwm_c15"      },   //Adder made in a lslice chain where this is the count output
  { "net_674",         "offset1_pwm_c14"      },
  { "net_682",         "offset1_pwm_c13"      },
  { "net_676",         "offset1_pwm_c12"      },
  { "net_680",         "offset1_pwm_c11"      },
  { "net_681",         "offset1_pwm_c10"      },
  { "net_685",         "offset1_pwm_c9"       },
  { "net_678",         "offset1_pwm_c8"       },
  { "net_677",         "offset1_pwm_c7"       },
  { "net_665",         "offset1_pwm_c6"       },
  { "net_663",         "offset1_pwm_c5"       },
  { "net_669",         "offset1_pwm_c4"       },
  { "net_670",         "offset1_pwm_c3"       },
  { "net_667",         "offset1_pwm_c2"       },
  { "net_666",         "offset1_pwm_c1"       },
  { "net_671",         "offset1_pwm_c0"       },
  
  { "net_179",         "ch2_offset_b0"        },
  { "net_59",          "ch2_offset_b1"        },
  { "net_64",          "ch2_offset_b2"        },
  { "net_208",         "ch2_offset_b3"        },
  { "net_207",         "ch2_offset_b4"        },
  { "net_217",         "ch2_offset_b5"        },
  { "net_178",         "ch2_offset_b6"        },
  { "net_211",         "ch2_offset_b7"        },
  { "net_219",         "ch2_offset_b8"        },
  { "net_222",         "ch2_offset_b9"        },
  { "net_291",         "ch2_offset_b10"       },
  { "net_475",         "ch2_offset_b11"       },
  { "net_306",         "ch2_offset_b12"       },
  { "net_302",         "ch2_offset_b13"       },
  { "net_314",         "ch2_offset_b14"       },
  { "net_287",         "ch2_offset_b15"       },

  { "net_73",          "offset2_pwm_r15"      },
  { "net_69",          "offset2_pwm_r14"      },
  { "net_71",          "offset2_pwm_r13"      },
  { "net_70",          "offset2_pwm_r12"      },
  { "net_72",          "offset2_pwm_r11"      },
  { "net_65",          "offset2_pwm_r10"      },
  { "net_67",          "offset2_pwm_r9"       },
  { "net_66",          "offset2_pwm_r8"       },
  { "net_68",          "offset2_pwm_r7"       },
  { "net_57",          "offset2_pwm_r6"       },
  { "net_60",          "offset2_pwm_r5"       },
  { "net_58",          "offset2_pwm_r4"       },
  { "net_61",          "offset2_pwm_r3"       },
  { "net_54",          "offset2_pwm_r2"       },
  { "net_56",          "offset2_pwm_r1"       },
  { "net_55",          "offset2_pwm_r0"       },
  
  { "net_584",         "sclk_div_h_b0"        },
  { "net_583",         "sclk_div_h_b1"        },
  { "net_478",         "sclk_div_h_b2"        },
  { "net_576",         "sclk_div_h_b3"        },
  { "net_574",         "sclk_div_h_b4"        },
  { "net_575",         "sclk_div_h_b5"        },
  { "net_573",         "sclk_div_h_b6"        },
  { "net_588",         "sclk_div_h_b7"        },
  { "net_488",         "sclk_div_h_b8"        },
  { "net_587",         "sclk_div_h_b9"        },
  { "net_581",         "sclk_div_h_b10"       },
  { "net_578",         "sclk_div_h_b11"       },
  { "net_486",         "sclk_div_h_b12"       },
  { "net_496",         "sclk_div_h_b13"       },
  { "net_740",         "sclk_div_h_b14"       },
  { "net_493",         "sclk_div_h_b15"       },
  { "net_749",         "sclk_div_h_b16"       },
  { "net_748",         "sclk_div_h_b17"       },
  { "net_491",         "sclk_div_h_b18"       },
  { "net_492",         "sclk_div_h_b19"       },
  { "net_643",         "sclk_div_h_b20"       },
  { "net_633",         "sclk_div_h_b21"       },
  { "net_631",         "sclk_div_h_b22"       },
  { "net_646",         "sclk_div_h_b23"       },
  { "net_647",         "sclk_div_h_b24"       },
  { "net_654",         "sclk_div_h_b25"       },
  { "net_498",         "sclk_div_h_b26"       },
  { "net_497",         "sclk_div_h_b27"       },
  { "net_657",         "sclk_div_h_b28"       },
  { "net_656",         "sclk_div_h_b29"       },
  { "net_655",         "sclk_div_h_b30"       },
  { "net_658",         "sclk_div_h_b31"       },

  { "net_735",         "sclk_div_l_b0"        },
  { "net_1009",        "sclk_div_l_b1"        },
  { "net_1007",        "sclk_div_l_b2"        },
  { "net_1018",        "sclk_div_l_b3"        },
  { "net_1016",        "sclk_div_l_b4"        },
  { "net_1017",        "sclk_div_l_b5"        },
  { "net_1015",        "sclk_div_l_b6"        },
  { "net_1024",        "sclk_div_l_b7"        },
  { "net_742",         "sclk_div_l_b8"        },
  { "net_1023",        "sclk_div_l_b9"        },
  { "net_743",         "sclk_div_l_b10"       },
  { "net_1038",        "sclk_div_l_b11"       },
  { "net_1035",        "sclk_div_l_b12"       },
  { "net_1037",        "sclk_div_l_b13"       },
  { "net_1034",        "sclk_div_l_b14"       },
  { "net_1054",        "sclk_div_l_b15"       },
  { "net_388",         "sclk_div_l_b16"       },
  { "net_1053",        "sclk_div_l_b17"       },
  { "net_1051",        "sclk_div_l_b18"       },
  { "net_1070",        "sclk_div_l_b19"       },
  { "net_1067",        "sclk_div_l_b20"       },
  { "net_1069",        "sclk_div_l_b21"       },
  { "net_1066",        "sclk_div_l_b22"       },
  { "net_1084",        "sclk_div_l_b23"       },
  { "net_833",         "sclk_div_l_b24"       },
  { "net_1083",        "sclk_div_l_b25"       },
  { "net_1082",        "sclk_div_l_b26"       },
  { "net_1090",        "sclk_div_l_b27"       },
  { "net_1088",        "sclk_div_l_b28"       },
  { "net_1089",        "sclk_div_l_b29"       },
  { "net_1087",        "sclk_div_l_b30"       },
  { "net_1091",        "sclk_div_l_b31"       },

  { "net_1294",        "clk_a_div_out15"      },
  { "net_1281",        "clk_a_div_out14"      },
  { "net_1289",        "clk_a_div_out13"      },
  { "net_1284",        "clk_a_div_out12"      },
  { "net_1287",        "clk_a_div_out11"      },
  { "net_1288",        "clk_a_div_out10"      },
  { "net_1283",        "clk_a_div_out9"       },
  { "net_1286",        "clk_a_div_out8"       },
  { "net_1285",        "clk_a_div_out7"       },
  { "net_1271",        "clk_a_div_out6"       },
  { "net_1276",        "clk_a_div_out5"       },
  { "net_1272",        "clk_a_div_out4"       },
  { "net_1274",        "clk_a_div_out3"       },
  { "net_1269",        "clk_a_div_out2"       },
  { "net_1270",        "clk_a_div_out1"       },
  { "net_1275",        "clk_a_div_out0"       },

  { "net_1290",        "clk_a_div_reg15"      },
  { "net_1261",        "clk_a_div_reg14"      },
  { "net_1201",        "clk_a_div_reg13"      },
  { "net_1279",        "clk_a_div_reg12"      },
  { "net_1278",        "clk_a_div_reg11"      },
  { "net_1280",        "clk_a_div_reg10"      },
  { "net_1273",        "clk_a_div_reg9"       },
  { "net_1291",        "clk_a_div_reg8"       },
  { "net_1282",        "clk_a_div_reg7"       },
  { "net_1198",        "clk_a_div_reg6"       },
  { "net_1262",        "clk_a_div_reg5"       },
  { "net_1268",        "clk_a_div_reg4"       },
  { "net_1266",        "clk_a_div_reg3"       },
  { "net_1372",        "clk_a_div_reg2"       },
  { "net_1267",        "clk_a_div_reg1"       },
  { "net_1277",        "clk_a_div_reg0"       },

  { "net_1265",        "clk_a_div_a"          },
  { "net_1375",        "clk_a_div_b"          },
  { "net_1199",        "clk_a_div_c"          },
  { "net_1264",        "clk_a_div_d"          },
  { "net_1200",        "clk_a_reset"          },

  { "net_504",         "clk_100MHz"           },

  { "net_838",         "smp_rst_cnt_b3"       },
  { "net_835",         "smp_rst_cnt_b2"       },
  { "net_837",         "smp_rst_cnt_b1"       },
  { "net_836",         "smp_rst_cnt_b0"       },

  { "net_725",         "smp_rst_state"        },

  { "net_1085",        "smp_clk_l_cnt_out31"  },
  { "net_1073",        "smp_clk_l_cnt_out30"  },
  { "net_1079",        "smp_clk_l_cnt_out29"  },
  { "net_1077",        "smp_clk_l_cnt_out28"  },
  { "net_1080",        "smp_clk_l_cnt_out27"  },
  { "net_1072",        "smp_clk_l_cnt_out26"  },
  { "net_1075",        "smp_clk_l_cnt_out25"  },
  { "net_1078",        "smp_clk_l_cnt_out24"  },
  { "net_1074",        "smp_clk_l_cnt_out23"  },
  { "net_1058",        "smp_clk_l_cnt_out22"  },
  { "net_1055",        "smp_clk_l_cnt_out21"  },
  { "net_1062",        "smp_clk_l_cnt_out20"  },
  { "net_1064",        "smp_clk_l_cnt_out19"  },
  { "net_1056",        "smp_clk_l_cnt_out18"  },
  { "net_1060",        "smp_clk_l_cnt_out17"  },
  { "net_1063",        "smp_clk_l_cnt_out16"  },
  { "net_1059",        "smp_clk_l_cnt_out15"  },
  { "net_1048",        "smp_clk_l_cnt_out14"  },
  { "net_1049",        "smp_clk_l_cnt_out13"  },
  { "net_1041",        "smp_clk_l_cnt_out12"  },
  { "net_1044",        "smp_clk_l_cnt_out11"  },
  { "net_1045",        "smp_clk_l_cnt_out10"  },
  { "net_1040",        "smp_clk_l_cnt_out9"   },
  { "net_1043",        "smp_clk_l_cnt_out8"   },
  { "net_1042",        "smp_clk_l_cnt_out7"   },
  { "net_1029",        "smp_clk_l_cnt_out6"   },
  { "net_1026",        "smp_clk_l_cnt_out5"   },
  { "net_1031",        "smp_clk_l_cnt_out4"   },
  { "net_1032",        "smp_clk_l_cnt_out3"   },
  { "net_1027",        "smp_clk_l_cnt_out2"   },
  { "net_1030",        "smp_clk_l_cnt_out1"   },
  { "net_1033",        "smp_clk_l_cnt_out0"   },

  { "net_1081",        "smp_clk_l_cnt_reg31"  },
  { "net_1191",        "smp_clk_l_cnt_reg30"  },
  { "net_1086",        "smp_clk_l_cnt_reg29"  },
  { "net_1071",        "smp_clk_l_cnt_reg28"  },
  { "net_1068",        "smp_clk_l_cnt_reg27"  },
  { "net_1193",        "smp_clk_l_cnt_reg26"  },
  { "net_1192",        "smp_clk_l_cnt_reg25"  },
  { "net_1076",        "smp_clk_l_cnt_reg24"  },
  { "net_1065",        "smp_clk_l_cnt_reg23"  },
  { "net_1190",        "smp_clk_l_cnt_reg22"  },
  { "net_1186",        "smp_clk_l_cnt_reg21"  },
  { "net_1057",        "smp_clk_l_cnt_reg20"  },
  { "net_1052",        "smp_clk_l_cnt_reg19"  },
  { "net_1187",        "smp_clk_l_cnt_reg18"  },
  { "net_1188",        "smp_clk_l_cnt_reg17"  },
  { "net_1061",        "smp_clk_l_cnt_reg16"  },
  { "net_1050",        "smp_clk_l_cnt_reg15"  },
  { "net_415",         "smp_clk_l_cnt_reg14"  },
  { "net_259",         "smp_clk_l_cnt_reg13"  },
  { "net_1039",        "smp_clk_l_cnt_reg12"  },
  { "net_1036",        "smp_clk_l_cnt_reg11"  },
  { "net_1046",        "smp_clk_l_cnt_reg10"  },
  { "net_1189",        "smp_clk_l_cnt_reg9"   },
  { "net_1184",        "smp_clk_l_cnt_reg8"   },
  { "net_1047",        "smp_clk_l_cnt_reg7"   },
  { "net_1185",        "smp_clk_l_cnt_reg6"   },
  { "net_1010",        "smp_clk_l_cnt_reg5"   },
  { "net_1028",        "smp_clk_l_cnt_reg4"   },
  { "net_1021",        "smp_clk_l_cnt_reg3"   },
  { "net_1008",        "smp_clk_l_cnt_reg2"   },
  { "net_1022",        "smp_clk_l_cnt_reg1"   },
  { "net_1025",        "smp_clk_l_cnt_reg0"   },

  { "net_652",         "smp_clk_l_cnt_out31"  },
  { "net_637",         "smp_clk_l_cnt_out30"  },
  { "net_642",         "smp_clk_l_cnt_out29"  },
  { "net_640",         "smp_clk_l_cnt_out28"  },
  { "net_644",         "smp_clk_l_cnt_out27"  },
  { "net_635",         "smp_clk_l_cnt_out26"  },
  { "net_636",         "smp_clk_l_cnt_out25"  },
  { "net_641",         "smp_clk_l_cnt_out24"  },
  { "net_638",         "smp_clk_l_cnt_out23"  },
  { "net_622",         "smp_clk_l_cnt_out22"  },
  { "net_628",         "smp_clk_l_cnt_out21"  },
  { "net_624",         "smp_clk_l_cnt_out20"  },
  { "net_629",         "smp_clk_l_cnt_out19"  },
  { "net_621",         "smp_clk_l_cnt_out18"  },
  { "net_623",         "smp_clk_l_cnt_out17"  },
  { "net_627",         "smp_clk_l_cnt_out16"  },
  { "net_620",         "smp_clk_l_cnt_out15"  },
  { "net_605",         "smp_clk_l_cnt_out14"  },
  { "net_610",         "smp_clk_l_cnt_out13"  },
  { "net_607",         "smp_clk_l_cnt_out12"  },
  { "net_611",         "smp_clk_l_cnt_out11"  },
  { "net_612",         "smp_clk_l_cnt_out10"  },
  { "net_606",         "smp_clk_l_cnt_out9"   },
  { "net_609",         "smp_clk_l_cnt_out8"   },
  { "net_608",         "smp_clk_l_cnt_out7"   },
  { "net_592",         "smp_clk_l_cnt_out6"   },
  { "net_590",         "smp_clk_l_cnt_out5"   },
  { "net_595",         "smp_clk_l_cnt_out4"   },
  { "net_596",         "smp_clk_l_cnt_out3"   },
  { "net_591",         "smp_clk_l_cnt_out2"   },
  { "net_594",         "smp_clk_l_cnt_out1"   },
  { "net_597",         "smp_clk_l_cnt_out0"   },

  { "net_645",         "smp_clk_l_cnt_reg31"  },
  { "net_750",         "smp_clk_l_cnt_reg30"  },
  { "net_649",         "smp_clk_l_cnt_reg29"  },
  { "net_634",         "smp_clk_l_cnt_reg28"  },
  { "net_632",         "smp_clk_l_cnt_reg27"  },
  { "net_651",         "smp_clk_l_cnt_reg26"  },
  { "net_653",         "smp_clk_l_cnt_reg25"  },
  { "net_639",         "smp_clk_l_cnt_reg24"  },
  { "net_630",         "smp_clk_l_cnt_reg23"  },
  { "net_617",         "smp_clk_l_cnt_reg22"  },
  { "net_626",         "smp_clk_l_cnt_reg21"  },
  { "net_618",         "smp_clk_l_cnt_reg20"  },
  { "net_615",         "smp_clk_l_cnt_reg19"  },
  { "net_625",         "smp_clk_l_cnt_reg18"  },
  { "net_619",         "smp_clk_l_cnt_reg17"  },
  { "net_616",         "smp_clk_l_cnt_reg16"  },
  { "net_614",         "smp_clk_l_cnt_reg15"  },
  { "net_599",         "smp_clk_l_cnt_reg14"  },
  { "net_601",         "smp_clk_l_cnt_reg13"  },
  { "net_613",         "smp_clk_l_cnt_reg12"  },
  { "net_598",         "smp_clk_l_cnt_reg11"  },
  { "net_602",         "smp_clk_l_cnt_reg10"  },
  { "net_604",         "smp_clk_l_cnt_reg9"   },
  { "net_600",         "smp_clk_l_cnt_reg8"   },
  { "net_603",         "smp_clk_l_cnt_reg7"   },
  { "net_566",         "smp_clk_l_cnt_reg6"   },
  { "net_568",         "smp_clk_l_cnt_reg5"   },
  { "net_593",         "smp_clk_l_cnt_reg4"   },
  { "net_585",         "smp_clk_l_cnt_reg3"   },
  { "net_567",         "smp_clk_l_cnt_reg2"   },
  { "net_586",         "smp_clk_l_cnt_reg1"   },
  { "net_589",         "smp_clk_l_cnt_reg0"   },
  
  { "net_487",         "smp_read_offset_b0"   },  //Sample read address offset input from MCU mixed with register and counter
  { "net_746",         "smp_read_offset_b1"   },  //On every read by the MCU the counter is incremented and loaded into the register
  { "net_500",         "smp_read_offset_b2"   },
  { "net_499",         "smp_read_offset_b3"   },
  { "net_483",         "smp_read_offset_b4"   },
  { "net_494",         "smp_read_offset_b5"   },
  { "net_744",         "smp_read_offset_b6"   },
  { "net_495",         "smp_read_offset_b7"   },
  { "net_741",         "smp_read_offset_b8"   },
  { "net_650",         "smp_read_offset_b9"   },
  { "net_479",         "smp_read_offset_b10"  },
  { "net_490",         "smp_read_offset_b11"  },

  { "net_391",        "smp_read_offset_r0"    },  //Sample read address offset register
  { "net_392",        "smp_read_offset_r1"    },
  { "net_393",        "smp_read_offset_r2"    },
  { "net_485",        "smp_read_offset_r3"    },
  { "net_733",        "smp_read_offset_r4"    },
  { "net_312",        "smp_read_offset_r5"    },
  { "net_382",        "smp_read_offset_r6"    },
  { "net_394",        "smp_read_offset_r7"    },
  { "net_402",        "smp_read_offset_r8"    },
  { "net_315",        "smp_read_offset_r9"    },
  { "net_383",        "smp_read_offset_r10"   },
  { "net_484",        "smp_read_offset_r11"   },

  { "net_403",        "smp_read_offset_c11"   },  //Sample read address offset counter
  { "net_398",        "smp_read_offset_c10"   },
  { "net_400",        "smp_read_offset_c9"    },
  { "net_399",        "smp_read_offset_c8"    },
  { "net_401",        "smp_read_offset_c7"    },
  { "net_397",        "smp_read_offset_c6"    },
  { "net_396",        "smp_read_offset_c5"    },
  { "net_390",        "smp_read_offset_c4"    },
  { "net_395",        "smp_read_offset_c3"    },
  { "net_384",        "smp_read_offset_c2"    },
  { "net_385",        "smp_read_offset_c1"    },
  { "net_387",        "smp_read_offset_c0"    },

  { "net_659",         "smp_clk_enable"       },

  { "net_353",         "cmd3C_b0"             },
  { "net_379",         "cmd3C_b1"             },
  { "net_277",         "cmd3C_b2"             },
  { "net_275",         "cmd3C_b3"             },
  { "net_555",         "cmd3C_b4"             },
  { "net_559",         "cmd3C_b5"             },
  { "net_363",         "cmd3C_b6"             },
  { "net_454",         "cmd3C_b7"             },
  { "net_286",         "cmd3C_b8"             },
  { "net_280",         "cmd3C_b9"             },
  { "net_279",         "cmd3C_b10"            },
  { "net_189",         "cmd3C_b11"            },
  { "net_737",         "cmd3C_b12"            },
  { "net_194",         "cmd3C_b13"            },
  { "net_296",         "cmd3C_b14"            },
  { "net_297",         "cmd3C_b15"            },

  { "net_582",         "mcu_d00000xxx"        },
  { "net_489",         "mcu_d000000xx"        },
  { "net_579",         "mcu_d0000010x"        },

  { "net_716",         "byte_state_0"         },
  { "net_731",         "byte_state_1"         },

  { "net_1181",        "state_b0"             },
  { "net_1178",        "state_b1"             },
  { "net_1177",        "state_b2"             },
  { "net_1259",        "state_b3"             },

  { "net_1349",         "state_sum_b0"        },
  { "net_1350",         "state_sum_b1"        },
  { "net_1346",         "state_sum_b2"        },
  { "net_1352",         "state_sum_b3"        },

  { "net_170",         "cmdxxxxxx11_select"   },

  { "net_197",         "cmdxxxx01xx_select"   },

  { "net_266",         "cmdxxxx0001_select"   },

  { "net_196",         "cmd001000xx_select"   },
  { "net_265",         "cmd0001x000_select"   },  //For command 0x10 and 0x18 which are not used in the software ???

  { "net_476",         "cmd0x_data_write"     },
  { "net_183",         "cmd1x_data_write"     },

  { "net_361",         "cmd_0D_0E_select"     },

  { "net_442",         "cmd0x_select"         },
  { "net_564",         "cmd1x_select"         },
  { "net_450",         "cmd2x_select"         },
  { "net_453",         "cmd3x_select"         },
  { "net_452",         "cmd6x_select"         },

  { "net_549",         "cmd05_select"         },
  { "net_548",         "cmd06_select"         },  //Read fpga version 0x1432
  { "net_552",         "cmd0A_select"         },  //Read a wait flag
  { "net_285",         "cmd0D_select"         },
  { "net_732",         "cmd0E_select"         },
  { "net_466",         "cmd14_select"         },  //Read 2 bytes of data
  { "net_262",         "cmd21_select"         },
  { "net_172",         "cmd23_select"         },
  { "net_439",         "cmd24_select"         },
  { "net_540",         "cmd25_select"         },
  { "net_539",         "cmd26_select"         },
  { "net_440",         "cmd27_select"         },
  { "net_269",         "cmd32_select"         },
  { "net_264",         "cmd35_select"         },
  { "net_267",         "cmd38_select"         },
  { "net_359",         "cmd3C_select"         },
  { "net_445",         "cmd41_select"         },  //Read fixed value  0x8150
  { "net_430",         "cmd65_select"         },
  { "net_432",         "cmd68_select"         },  //Process the signals ---
  { "net_437",         "cmd69_select"         },
  { "net_356",         "cmd6A_select"         },
  { "net_177",         "cmd6B_select"         },
  { "net_274",         "cmd6C_select"         },
  { "net_271",         "cmd6D_select"         },
  { "net_352",         "cmd6E_select"         },  //---- to here

  { "net_473",         "cmd_6F_1F_select"     },

  { "net_468",         "not_cmd_41_14_06"     },  //True when not one of these commands selected in the command register
  { "net_976",         "not_cmd_05_0A"        },  //True when not one of these commands selected in the command register

  { "net_263",         "cmd01_enable"         },

  { "net_648",         "cmd0D_enable0"        },  //Load high byte
  { "net_747",         "cmd0D_enable1"        },
  { "net_577",         "cmd0D_enable2"        },
  { "net_580",         "cmd0D_enable3"        },  //Load low byte
  { "net_832",         "cmd0E_enable0"        },
  { "net_386",         "cmd0E_enable1"        },
  { "net_739",         "cmd0E_enable2"        },
  { "net_734",         "cmd0E_enable3"        },
  { "net_185",         "cmd0F_enable"         },

  { "net_429",         "cmd15_enable"         },
  { "net_455",         "cmd16_enable"         },
  { "net_338",         "cmd17_enable"         },
  { "net_184",         "cmd1A_enable"         },

  { "net_469",         "cmd1F_enable0"        },   //Name the bits
  { "net_288",         "cmd1F_enable1"        },

  { "net_719",         "cmd32_enable0"        },
  { "net_772",         "cmd32_enable1"        },
  { "net_572",         "cmd33_enable"         },
  { "net_570",         "cmd34_enable"         },
  { "net_294",         "cmd35_enable0"        },
  { "net_176",         "cmd35_enable1"        },
  { "net_456",         "cmd36_enable"         },
  { "net_472",         "cmd37_enable"         },
  { "net_171",         "cmd38_enable0"        },
  { "net_463",         "cmd38_enable1"        },

  { "net_276",         "cmd3C_enable0"        },
  { "net_282",         "cmd3C_enable1"        },


//  { "",         ""         },

  { 0,                 0                      }
};

//----------------------------------------------------------------------------------------------------------------------------------

NETRENAME clock_renaming_table[] =
{
  { "gclk_0",          "clock_200MHz"         },
  { "gclk_2",          "sample_read_clock"    },
  { "gclk_3",          "sample_write_clock"   },
  { "gclk_4",          "clk_100MHz"           },
  { "gclk_6",          "i_mcu_clk"            },
  { 0,                 0                      }
};

//----------------------------------------------------------------------------------------------------------------------------------


